processes:
  - name: containerd
    executable: /bin/sh
    args:
      - -c
      - /var/vcap/jobs/containerd/bin/start
    hooks:
      pre_start: /var/vcap/jobs/containerd/bin/bpm-pre-start
    unsafe:
      privileged: true
    additional_volumes:
      - path: /var/vcap/data/grootfs/store
        writable: true
        mount_only: true
      - path: /var/vcap/data/garden/depot
        writable: true
        mount_only: true
      - path: /var/vcap/data/containerd/runc/user
        writable: true
        mount_only: true
      - path: /var/vcap/data/containerd/sockets
        writable: true
        mount_only: true
      - path: /var/vcap/data/containerd/bin
        writable: true
        mount_only: true
        allow_executions: true

