- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "0.12.2"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.12.2"
    sha1: "f2edbf3d1417a253205338c9941ca989cd2f8331"

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/bpm?/enabled?
  value: true

- type: replace
  path: /instance_groups/name=garden/jobs/name=containerd?/properties/bpm?/enabled?
  value: true
