#!/usr/bin/env bash
set -ex

base=$PWD

cd "$( dirname "$0" )/../.."

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

cd src/code.cloudfoundry.org/garden-integration-tests

ginkgo --nodes=${GINKGO_NODES:-8} --failOnPending --randomizeSuites --randomizeAllSpecs "--focus=forwards the exit status even if stdin is still being written|when OverrideContainerLimits is not specified on the pea" -stream --trace
